update

diff --git a/main.yml b/main.yml
--- a/main.yml
+++ b/main.yml
@@ -62,6 +62,14 @@ Resources:
       ManagedPolicyArns:
         - arn:aws:iam::aws:policy/CloudWatchFullAccess
         - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy
+      Policies:
+        - PolicyDocument:
+            Version: "2012-10-17"
+            Statement:
+              - Effect: Allow
+                Action: 'ec2:DescribeTags'
+                Resource: '*'
+          PolicyName: ec2DescribeTags
       Tags:
         - Key: Name
           Value: !Ref AWS::StackName
@@ -93,30 +101,30 @@ Resources:
     Properties:
       Name: !Ref AWS::StackName
       ServiceRole: !GetAtt DeploymentRole.Arn
-      Artifacts:
+      Artifacts: # the build project output will be generated and handled inside codepipeline
         Type: CODEPIPELINE
       Environment:
         Type: LINUX_CONTAINER
         ComputeType: BUILD_GENERAL1_SMALL
         Image: aws/codebuild/standard:2.0
-      Source:
+      Source: # the source code to be built are specified in codepipeline inputartifact
         Type: CODEPIPELINE
         
   DeploymentApplication:
     Type: AWS::CodeDeploy::Application
     Properties:
       ApplicationName: !Ref AWS::StackName 
-      ComputePlatform: Server
+      ComputePlatform: Server # the platform which codedeploy will deploy the application to
 
-  StagingDeploymentGroup:
+  StagingDeploymentGroup: # a group that specifies which instances should receive update of this app
     Type: AWS::CodeDeploy::DeploymentGroup
-    DependsOn: Instance
+    DependsOn: Instance # this resource depends on the creation of resource named Instance, it will only be created after Instance has been created
     Properties:
       DeploymentGroupName: staging
-      ApplicationName: !Ref DeploymentApplication 
-      DeploymentConfigName: CodeDeployDefault.AllAtOnce  
+      ApplicationName: !Ref DeploymentApplication # the name of an existing codedeploy application to be associated with this group
+      DeploymentConfigName: CodeDeployDefault.AllAtOnce  # deploy to all instance at once depending on which config we choose
       ServiceRoleArn: !GetAtt DeploymentRole.Arn 
-      Ec2TagFilters:
+      Ec2TagFilters: # to select which ec2 instance we want to include in this deployment group based on its tag
         - Key: aws:cloudformation:stack-name 
           Type: KEY_AND_VALUE
           Value: !Ref AWS::StackName
@@ -125,22 +133,22 @@ Resources:
     Type: AWS::CodePipeline::Pipeline
     Properties:
       Name: !Ref AWS::StackName
-      ArtifactStore:
+      ArtifactStore: # the s3 bucket where the artifacts of the pipeline will be stored
         Location: !Ref CodePipelineBucket
         Type: S3
       RoleArn: !GetAtt DeploymentRole.Arn
       Stages:
-        - Name: Source
-          Actions:
+        - Name: Source # the name of this stage
+          Actions: # specify the action to be included during this stage
             - Name: Source
               ActionTypeId:
-                Category: Source
+                Category: Source # specifies what kind of valid action can be taken in this stage
                 Owner: ThirdParty
                 Version: '1'
                 Provider: GitHub
-              OutputArtifacts:
+              OutputArtifacts: # the name of the result of the action
                 - Name: Source
-              Configuration:
+              Configuration: # config for this action
                 Owner: !Ref GitHubOwner
                 Repo: !Ref GitHubRepo
                 Branch: !Ref GitHubBranch
@@ -155,9 +163,9 @@ Resources:
                 Owner: AWS
                 Provider: CodeBuild
                 Version: '1'
-              InputArtifacts:
+              InputArtifacts: # take the output from source above as input
                 - Name: Source
-              OutputArtifacts:
+              OutputArtifacts: # output to be send to next stage
                 - Name: Build
               Configuration:
                 ProjectName: !Ref BuildProject 
@@ -165,7 +173,7 @@ Resources:
         - Name: Staging
           Actions:
             - Name: Staging
-              InputArtifacts:
+              InputArtifacts: # take output from build stage above as input
                 - Name: Build
               ActionTypeId:
                 Category: Deploy
@@ -185,12 +193,91 @@ Resources:
         SecretToken: !Ref GitHubPersonalAccessToken
       Filters:
         - JsonPath: $.ref
-          MatchEquals: 'refs/heads/{Branch}'
-      TargetPipeline: !Ref Pipeline
-      TargetAction: Source
+          MatchEquals: 'refs/heads/{Branch}' # look up to TargetAction config for property called `Branch`
+      TargetPipeline: !Ref Pipeline # the name of the pipeline we want to connect to this webhook
+      TargetAction: Source # the name of an action in pipeline that we want to connect to this webhook
       Name: !Sub 'webhook-${AWS::StackName}'
       TargetPipelineVersion: !GetAtt Pipeline.Version
       RegisterWithThirdParty: true
+
+  InstanceLaunchTemplate:
+    Type: AWS::EC2::LaunchTemplate
+    Metadata:
+      AWS::CloudFormation::Init:
+        config:
+          packages:
+            yum:
+              ruby: []
+              jq: []
+            files:
+              /home/ec2-user/install:
+                source: !Sub "https://aws-codedeploy-${AWS::Region}.s3.amazonaws.com/latest/install"
+                mode: "000755"
+            commands:
+              00-install-cd-agent: 
+                command: "./install auto" 
+                cwd: "/home/ec2-user/"
+    Properties:
+      LaunchTemplateName: !Sub 'LaunchTemplate_${AWS::StackName}'
+      LaunchTemplateData:
+        ImageId: !Ref EC2AMI
+        InstanceType: !Ref EC2InstanceType
+        IamInstanceProfile:
+          Arn: !GetAtt InstanceProfile.Arn
+        Monitoring:
+          Enabled: true
+        SecurityGroupIds:
+          - !GetAtt SecurityGroup.GroupId
+        UserData: 
+          Fn::Base64:
+            !Sub |
+              #!/bin/bash -xe
+
+              # send script output to /tmp so we can debug boot failures
+              exec > /tmp/userdata.log 2>&1 
+
+              # Update all packages
+              yum -y update
+
+              # Get latest cfn scripts
+              yum install -y aws-cfn-bootstrap
+
+              cat > /tmp/install_script.sh << EOF  
+                # START
+                echo "Setting up NodeJS Environment"
+                curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
+
+                # Dot source the files to ensure that variables are available within the current shell
+                . /home/ec2-user/.nvm/nvm.sh
+                . /home/ec2-user/.bashrc
+
+                # Install NVM, NPM, Node.JS
+                nvm alias default v12.7.0
+                nvm install v12.7.0
+                nvm use v12.7.0
+
+                # Create log directory
+                mkdir -p /home/ec2-user/app/logs
+
+              EOF
+
+              chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x /tmp/install_script.sh
+              sleep 1; su - ec2-user -c "/tmp/install_script.sh" 
+
+              # Have CloudFormation install any files and packages from the metadata
+              /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource InstanceLaunchTemplate
+
+              # Query the EC2 metadata service for this instance's instance-id
+              export INSTANCE_ID=`curl -s http://169.254.169.254/latest/meta-data/instance-id`
+
+              # Query EC2 describeTags method and pull our the CFN Logical ID for this instance
+              export LOGICAL_ID=`aws --region ${AWS::Region} ec2 describe-tags \
+              --filters "Name=resource-id,Values=${!INSTANCE_ID}" \
+                        "Name=key,Values=aws:cloudformation:logical-id" \
+              | jq -r ".Tags[0].Value"`
+
+              # Signal to CloudFormation that the instance is ready
+              /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource ${!LOGICAL_ID}
 
 
   Instance:
@@ -199,78 +286,38 @@ Resources:
       ResourceSignal:
         Timeout: PT30M
         Count: 1
-    Metadata:
-      AWS::CloudFormation::Init:
-        config:
-          packages:
-            yum:
-              ruby: []
-          files:
-            /home/ec2-user/install:
-              source: !Sub "https://aws-codedeploy-${AWS::Region}.s3.amazonaws.com/latest/install"
-              mode: "000755"
-          commands:
-            00-install-cd-agent: 
-              command: "./install auto" 
-              cwd: "/home/ec2-user/"
     Properties:
-      ImageId: !Ref EC2AMI
-      InstanceType: !Ref EC2InstanceType
-      IamInstanceProfile: !Ref InstanceProfile
-      Monitoring: true
-      SecurityGroupIds:
-        - !GetAtt SecurityGroup.GroupId
-      UserData:
-        Fn::Base64: 
-          !Sub |
-            #!/bin/bash -xe
+      LaunchTemplate:
+        LaunchTemplateId: !Ref InstanceLaunchTemplate
+        Version: !GetAtt InstanceLaunchTemplate.LatestVersionNumber
+      Tags:
+        - Key: Name
+          Value: !Ref AWS::StackName
 
-            # send script output to /tmp so we can debug boot failures
-            exec > /tmp/userdata.log 2>&1 
-
-            # Update all packages
-            yum -y update
-
-            # Get latest cfn scripts
-            yum install -y aws-cfn-bootstrap
-
-            cat > /tmp/install_script.sh << EOF  
-              # START
-              echo "Setting up NodeJS Environment"
-              curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
-
-              # Dot source the files to ensure that variables are available within the current shell
-              . /home/ec2-user/.nvm/nvm.sh
-              . /home/ec2-user/.bashrc
-
-              # Install NVM, NPM, Node.JS
-              nvm alias default v12.7.0
-              nvm install v12.7.0
-              nvm use v12.7.0
-
-              # Create log directory
-              mkdir -p /home/ec2-user/app/logs
-
-            EOF
-
-            chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x /tmp/install_script.sh
-            sleep 1; su - ec2-user -c "/tmp/install_script.sh" 
-
-            # Have CloudFormation install any files and packages from the metadata
-            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
-
-            #Signal to CloudFormation that the instance is ready
-            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
-
+  Instance2:
+    Type: AWS::EC2::Instance
+    CreationPolicy:
+      ResourceSignal:
+        Timeout: PT30M
+        Count: 1
+    Properties:
+      LaunchTemplate:
+        LaunchTemplateId: !Ref InstanceLaunchTemplate
+        Version: !GetAtt InstanceLaunchTemplate.LatestVersionNumber
       Tags:
         - Key: Name
           Value: !Ref AWS::StackName
 
 
 Outputs:
-  InstanceEndpoint:
+  InstanceEndpoint1:
     Description: The DNS name for the created instance
     Value: !Sub "https://${Instance.PublicDnsName}:8080"
     Export:
-      Name: InstanceEndpoint
+      Name: InstanceEndpoint1
+  InstanceEndpoint2:
+    Description: The DNS name for the created instance
+    Value: !Sub "https://${Instance2.PublicDnsName}:8080"
+    Export:
+      Name: InstanceEndpoint2
   
